# Generated by Django 6.0.6 on 2026-08-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_sessionface_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionface',
            name='image_url',
        ),
    ]
