# Generated by Django 6.0.6 on 2026-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_face_url',
        ),
        migrations.AddField(
            model_name='student',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
